### ISSUE TITLE
raise NotImplemented for symbolic relations

### ISSUE THREAD

**Issue by rwst** [symengine/symengine.py#12]
(heavily edited)
From https://github.com/symengine/symengine/issues/356

As long as relations are not implemented in symengine we should not return `True` or `False` for any symbolic inequality.

So at the moment the only way to conform to SymPy behaviour is by returning a SymPy Rel.

**Comment by Sumith1896** [comment]
+1

**Comment by rwst** [comment]
Description updated.

**Comment by rwst** [comment]
Actually, it's possible to just create and return the unevaluated relation, stay tuned.

**Comment by certik** [comment]
The other way to fix that is to raise an exception until it is implemented using SymEngine. The solution that @rwst implemented is fine with me.
