### ISSUE TITLE
expr.atoms() seems to be broken on 0.1.0.dev

### ISSUE THREAD

**Issue by phantomas1234** [symengine/symengine.py#121]
In [19]: import symengine

	In [20]: import sympy

	In [21]: (symengine.var('x') + symengine.var('y')).atoms()
	Out[21]: set()

	In [22]: (sympy.var('x') + sympy.var('y')).atoms()
	Out[22]: {x, y}

on symengine.py=='0.1.0.dev' and symengine==0.2.0  (both installed using conda). On #59  `atoms` has been checked off as done. `free_symbols` seems to work fine.

	In [25]: (sympy.var('x') + sympy.var('y')).free_symbols
	Out[25]: {x, y}

	In [26]: (symengine.var('x') + symengine.var('y')).free_symbols
	Out[26]: {x, y}

**Comment by isuruf** [comment]
This is an issue on master as well. `(x+y).atoms(Symbol)` works, but not `(x+y).atoms()`
