### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Shekharrajak** [symengine/symengine.py#181]
I did `pip install symengine`

and run `ipython` in my terminal 

```

In [3]: from symengine import *

In [4]:  var("x y z")
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-d541776bcee5> in <module>()
----> 1 var("x y z")

NameError: name 'var' is not defined

In [5]: x, y, z = symbols("x, y, z")
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-3b4cfa0ee327> in <module>()
----> 1 x, y, z = symbols("x, y, z")
```

Even I installed it through conda but it is not working. 
What else I need to do ?

**Comment by Shekharrajak** [comment]
I also tried to [build from the source](https://github.com/symengine/symengine.py#build-from-source) , but I got some error .  The error is something like that : 
```
/usr/local/lib/cmake/symengine/../../../include/symengine/mp_wrapper.h:361:35: error: no member named 'get_mpz_t' in 'SymEngine::mpz_wrapper'
```

**Comment by Shekharrajak** [comment]
Ping @isuruf

**Comment by isuruf** [comment]
In the pip install case, can you check if `symengine/utilities.py` file is there?

**Comment by isuruf** [comment]
Do you still get this error?

**Comment by Shekharrajak** [comment]
Sorry for late response.

> In the pip install case, can you check if symengine/utilities.py file is there?

where should I check the file?

**Comment by Shekharrajak** [comment]
I reinstalled it. Now it is working fine. Thanks!
