### ISSUE TITLE
Symengine does not work anymore

### ISSUE THREAD

**Issue by BlackTeaAndCoffee** [symengine/symengine.py#183]
Hi, 

last week i was on Euroscipy 2017. So  i installed various different kind of packages. 
Today i wanted to change some bits of my code, and suddenly symengine didn't work anymore. 

so i removed symengine, and then run 

conda install python-symengine -c symengine -c conda-forge

i get
```
running install
running build
running build_ext
CMake Error at CMakeLists.txt:5 (find_package):
  Could not find a configuration file for package "SymEngine" that is
  compatible with requested version "0.3.0".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/symengine/SymEngineConfig.cmake, version: 0.2.0
    /usr/lib/cmake/symengine/SymEngineConfig.cmake, version: 0.2.0



-- Configuring incomplete, errors occurred!
See also "/home/mustafa/SymEngine/symengine.py/build/lib.linux-i686-3.6/CMakeFiles/CMakeOutput.log".
error: error calling cmake
mustafa@mustafa-Aspire-5749:~/SymEngine/symengine.py$ cd
mustafa@mustafa-Aspire-5749:~$ conda install python-symengine -c symengine -c conda-forge
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:
            
  - python-symengine

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/symengine/linux-32
  - https://conda.anaconda.org/symengine/noarch
  - https://conda.anaconda.org/conda-forge/linux-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/free/linux-32
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-32
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-32
  - https://repo.continuum.io/pkgs/pro/noarch
            

mustafa@mustafa-Aspire-5749:~$ pip3 install python3-symengine
Collecting python3-symengine
  Could not find a version that satisfies the requirement python3-symengine (from versions: )
No matching distribution found for python3-symengine

```
I think that me having an old laptop with 32 bandwidth is the problem. I'm not that 
experienced, so help would be very much appreciated.

**Comment by isuruf** [comment]
conda packages are 64-bit, so you can't use that.

Try `pip install symengine` or `pip3 install symengine`

**Comment by BlackTeaAndCoffee** [comment]
when i run pip3 install symengine 

i get 

Requirement already satisfied: symengine in /usr/lib/python3/dist-packages

but in the python console, when i run

import symengine 

i get 

```
Python 3.6.1 |Anaconda 4.4.0 (32-bit)| (default, May 11 2017, 13:08:54) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import symengine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'symengine'

```

**Comment by isuruf** [comment]
Can you check what `which pip3` and `which pip` gives you?
You can do `python -m pip install symengine`

**Comment by BlackTeaAndCoffee** [comment]
which pip3 gives me 

/usr/local/bin/pip3

running ```python -m pip install symengine   ``` gives me

```
Collecting symengine
  Using cached symengine-0.3.0.tar.gz
Building wheels for collected packages: symengine
  Running setup.py bdist_wheel for symengine ... error
  Complete output from command /home/mustafa/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tdble22v/symengine/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpqbk_te1opip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 5.4.0
  -- The CXX compiler identification is GNU 5.4.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:5 (find_package):
    Could not find a configuration file for package "SymEngine" that is
    compatible with requested version "0.3.0".
  
    The following configuration files were considered but not accepted:
  
      /usr/lib/cmake/symengine/SymEngineConfig.cmake, version: 0.2.0
      /usr/lib/cmake/symengine/SymEngineConfig.cmake, version: 0.2.0
  
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-build-tdble22v/symengine/build/lib.linux-i686-3.6/CMakeFiles/CMakeOutput.log".
  error: error calling cmake
  
  ----------------------------------------
  Failed building wheel for symengine
  Running setup.py clean for symengine
Failed to build symengine
Installing collected packages: symengine
  Running setup.py install for symengine ... error
    Complete output from command /home/mustafa/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tdble22v/symengine/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4r4c9bg9-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    CMake Error at CMakeLists.txt:5 (find_package):
      Could not find a configuration file for package "SymEngine" that is
      compatible with requested version "0.3.0".
    
      The following configuration files were considered but not accepted:
    
        /usr/lib/cmake/symengine/SymEngineConfig.cmake, version: 0.2.0
        /usr/lib/cmake/symengine/SymEngineConfig.cmake, version: 0.2.0
    
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-tdble22v/symengine/build/lib.linux-i686-3.6/CMakeFiles/CMakeOutput.log".
    error: error calling cmake
    
    ----------------------------------------
Command "/home/mustafa/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tdble22v/symengine/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4r4c9bg9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-tdble22v/symengine/
```

**Comment by isuruf** [comment]
Can you do `conda install wheel` and then do `python -m pip install symengine`?

**Comment by BlackTeaAndCoffee** [comment]
by running  ```conda install wheel``` i get 

``` Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/mustafa/anaconda3:
#
wheel                     0.29.0                   py36_0  ```

and with ``` python -m pip install symengine``` i get 

```
Collecting symengine
  Using cached symengine-0.3.0.tar.gz
Building wheels for collected packages: symengine
  Running setup.py bdist_wheel for symengine ... error
  Complete output from command /home/mustafa/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-moabq5q8/symengine/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp955pp5nlpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 5.4.0
  -- The CXX compiler identification is GNU 5.4.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:5 (find_package):
    Could not find a configuration file for package "SymEngine" that is
    compatible with requested version "0.3.0".
  
    The following configuration files were considered but not accepted:
  
      /usr/lib/cmake/symengine/SymEngineConfig.cmake, version: 0.2.0
      /usr/lib/cmake/symengine/SymEngineConfig.cmake, version: 0.2.0
  
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-build-moabq5q8/symengine/build/lib.linux-i686-3.6/CMakeFiles/CMakeOutput.log".
  error: error calling cmake
  
  ----------------------------------------
  Failed building wheel for symengine
  Running setup.py clean for symengine
Failed to build symengine
Installing collected packages: symengine
  Running setup.py install for symengine ... error
    Complete output from command /home/mustafa/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-moabq5q8/symengine/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6ut7rm0q-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    CMake Error at CMakeLists.txt:5 (find_package):
      Could not find a configuration file for package "SymEngine" that is
      compatible with requested version "0.3.0".
    
      The following configuration files were considered but not accepted:
    
        /usr/lib/cmake/symengine/SymEngineConfig.cmake, version: 0.2.0
        /usr/lib/cmake/symengine/SymEngineConfig.cmake, version: 0.2.0
    
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-moabq5q8/symengine/build/lib.linux-i686-3.6/CMakeFiles/CMakeOutput.log".
    error: error calling cmake
    
    ----------------------------------------
Command "/home/mustafa/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-moabq5q8/symengine/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6ut7rm0q-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-moabq5q8/symengine/

```

**Comment by isuruf** [comment]
I just checked and the pip wheels are not created for 32-bit as well. 32-bit is very rare these days, and I didn't think anybody would be using 32-bit Linux.
You'll have to install symengine, the C++ library manually before installing symengine.py.

**Comment by BlackTeaAndCoffee** [comment]
Ok,

well at least, i was right in thinking that it was a problem with 32-bit. Thanks for your effort. I will try that out. 

Best wishes

**Comment by isuruf** [comment]
I'm going to close this as you need to install the C++ library since we are not providing pre-built wheels for 32-bit systems.
