### ISSUE TITLE
Using latest version of symengine.py on Windows and Python 2.7

### ISSUE THREAD

**Issue by xwan242** [symengine/symengine.py#189]
Are there any potential issues to be aware of with using SymEngine 0.3 on Windows Python 2.7, since I'm guessing that this is not strictly supported given the lack of wheels available?

**Comment by isuruf** [comment]
Issue is that on windows, recommended compiler to compile extensions for python 2.7 is MSVC 2008, but symengine needs MSVC 2015 or higher. You could use MinGW to compile symengine and symengine.py, but this is not officially supported by python. That's why the wheels are not available officially.

**Comment by xwan242** [comment]
Thanks, I followed the steps in https://ci.appveyor.com/project/isuruf/symengine-py-l1jmr/build/122/job/nwquccv3684ahfxv and it seems to have worked well.
