### ISSUE TITLE
symengine.py does not support current symengine

### ISSUE THREAD

**Issue by woodscn** [symengine/symengine.py#22]
Building symengine.py requires a specific commit of symengine. This is undocumented. 

```
git checkout 3a1152fdafc83f8d1f35004b5bcda08f355e57c3
```

**Comment by certik** [comment]
Thanks @woodscn for reporting it. Indeed, we need to document this better, currently this is only "documented" here: https://github.com/symengine/symengine.py/blob/83c1a70cd2516a597a7a8a12ef0c0ce21ed825de/.travis.yml#L111

**Comment by Sumith1896** [comment]
The README does it have now https://github.com/symengine/symengine.py/blob/master/README.md#installation
Also after this PR https://github.com/symengine/symengine.py/pull/29 there will be a `symengine_version.txt` file.

**Comment by rwst** [comment]
I have problems understanding the issue because current symengine.py does not compile with that version mentioned, while it does with current symengine. So, is this still an issue?

**Comment by isuruf** [comment]
Closing the issue as this is now documented in README.md

**Comment by isuruf** [comment]
To clarify, `symengine.py` supports only the version mentioned in README.md, but current `symengine` master may work as well. `symengine.py` will be updated from time to time to work with the latest `symengine` master
