### ISSUE TITLE
Implement expr.diff(x, n) where n is an integer

### ISSUE THREAD

**Issue by BlackTeaAndCoffee** [symengine/symengine.py#224]
Hi i wanted to calculate the derivative of some big functions, and i thought 
that symengine would also use the diff method as in sympy and symengine has a diff method.
But doing so, i get a wrong result. Even for smaller functions i get 
wrong results. See following code:
```
import symengine as si
x = si.symbols('x')
print(si.diff(x**2, 1))
```
This gives zero. I've got symengine version 0.3.0.

Best Wishes 
BlackTea

**Comment by bjodah** [comment]
You need to specify the symbol which you want to take the derivative with respect to (`x` in this case) instead of `1`.

**Comment by bjodah** [comment]
I see, yes SymPy's syntax supports multiple ways of doing this. Arguably `symengine.py` should reproduce that behaviour. In the mean time you can do this:
```
>>> si.diff(x**2, x, x)
2
```
or more generally:
```
>>> si.diff(x**47, *[x]*13)
875997661345462656000*x**34
```
This would limit the highest derivative to 254th derivative on python <=3.6 (and some much higher number on Python 3.7).

**Comment by BlackTeaAndCoffee** [comment]
Alright! Thank you very much!

**Comment by isuruf** [comment]
> Arguably symengine.py should reproduce that behaviour

Yes, I agree.

> This would limit the highest derivative to 254th derivative on python <=3.6

Not if you put the arguments in a tuple. For eg: `si.diff(x**400, *[x]*300)` works.
