### ISSUE TITLE
Cannot convert Rational to float

### ISSUE THREAD

**Issue by Wrzlprmft** [symengine/symengine.py#227]
``` Python
from symengine import Rational
x = Rational(2,3)
print(float(x))
```

raises a `TypeError`.

The best workaround I found so far is `float(x.n().real_part())`.

**Comment by certik** [comment]
@Wrzlprmft thank you for the bug report. @isuruf fixed it in #265.

**Comment by Wrzlprmft** [comment]
Unfortunately the fix (or some other recent change) seems to destroy my work-around (see https://github.com/neurophysik/jitcdde/issues/17). More specifically, `sympy.Float(42).real_part` does not exist (only `sympy.Float(42).real`).

Can you either make a release (that allows me to pinpoint the version requirements) or implement a `real_part` attribute for Floats for backwards compatibility? Since everything is hardcoded, I can not monkey-patch this either.

**Comment by isuruf** [comment]
That fix should be backwards compatible. Which version of symengine are you using?

**Comment by Wrzlprmft** [comment]
> That fix should be backwards compatible. Which version of symengine are you using?

I am comparing a version I pulled a few minutes ago from GitHub and the latest pre-release from PyPI (0.3.1.dev1). What I need something that converts any of SymEngine’s non-complex number types (Integer, Rational, Float, …) to a Python `float` and works in both of these versions (or a new release/pre-release).

Suppose `x` is my SymEngine number (e.g., `x=symengine.Rational(2,3)`). In the current version, I can just use `float(x)`, but that does not work in the pre-release. In the pre-release I can use `float(x.n().real_part())` but that does not work in the current version (“'RealDouble' object has no attribute 'real_part'”); the closest I can get is `float(x.n().real)`.

**Comment by certik** [comment]
@Wrzlprmft is the issue that you are trying to make your code work with multiple versions of symengine?

Could one have a check based on a version of symengine and do what works for each? I understand that's not ideal, but at least it's some way forward.

**Comment by isuruf** [comment]
@Wrzlprmft, use `float(x.n(real=True))` which should work in both versions.

**Comment by Wrzlprmft** [comment]
> @Wrzlprmft is the issue that you are trying to make your code work with multiple versions of symengine?

Correct. Alternatively, I can deal with this using explicitly requiring a version, but that would require a release.

> Could one have a check based on a version of symengine and do what works for each? I understand that's not ideal, but at least it's some way forward.

`sympy.__version__` returns `0.3.1.dev1` in both cases, so that wouldn’t work. What I could do is to catch the exception, but I see no easy way to avoid catching some real problems due to faulty user input or similar. Anyway:

> @Wrzlprmft, use `float(x.n(real=True))` which should work in both versions.

Indeed. That solves my problem. Thank you.

**Comment by certik** [comment]
@Wrzlprmft perfect, I am glad it's solved. Sorry about the inconvenience.
