### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by BlackTeaAndCoffee** [symengine/symengine.py#232]
Hi i want to create a docker image of my project, but i have trouble installing 
symengine. 

For example, with the base image of frolvlad-alpine, i can easily pip install numpy or sympy. 
But symengine doesn't work. I tried to install the c++ library first, but still it doesn't work.

I am just not able to make it work. Has any one of you got it to work?
If so, can i have the dockerfile, please?

Best wishes 
Black Tea

**Comment by isuruf** [comment]
Do you have a Dockerfile that you tried installing symengine? If you post it here, we can figure out what went wrong.

**Comment by BlackTeaAndCoffee** [comment]
[Dockerfile.txt](https://github.com/symengine/symengine.py/files/2032404/Dockerfile.txt)
So right now, i got it actually to work. But only partially, if uncomment the "FROM frolvlad-alpine" line, 
it doesn't work anymore. 

I am fairly new to docker. :)

**Comment by isuruf** [comment]
>  But only partially, if uncomment the "FROM frolvlad-alpine" line,
it doesn't work anymore.

You can't have two `FROM` lines in one docker file.

**Comment by BlackTeaAndCoffee** [comment]
> You can't have two FROM lines in one docker file.

Ok, i just saw some dockerfiles which had this, but since it doesn't work for me, 
i probably just saw some shitty dockerfiles. 

Thanks anyway!
