### ISSUE TITLE
Cannot import cse (conda install)

### ISSUE THREAD

**Issue by Melisius** [symengine/symengine.py#247]
Hi,

I installed symengine via the conda route, but I am unable to import cse.
I tried to import it just as in the test example

**Comment by bjodah** [comment]
I think `cse` is only available in the "dev" version at the moment:
```
$ conda install -c symengine/label/dev python-symengine
```

**Comment by Melisius** [comment]
Tried installing by the above command in a new conda environment. It seems like cse is not in the dev-version in conda.

from symengine import cse
> ImportError: cannot import name 'cse'

**Comment by bjodah** [comment]
That's confusing, I literally did that and it worked. I'm on linux64 (files
are at anaconda.org/symengine)

**Comment by Melisius** [comment]
I'll try install it on a linux computer (I am on windows and installed it though windows-linux subsystem, maybe that have made an unexpected problem)

**Comment by isuruf** [comment]
Did you check that the symengine you are using is the one you installed? `import symengine; print(symengine.__file__)` should tell you where symengine is coming from.

**Comment by Melisius** [comment]
I think this screen-shot shows what I have done, https://imgur.com/ikXHsXi

When I install with the given command, it says that all requested packages are installed.
I cannot import cse from symengine
print(symengine.__file__) points to the expected folder.

**Comment by isuruf** [comment]
Can you show the output of `conda info`?

**Comment by Melisius** [comment]
conda install -c symengine/label/dev -c conda-forge python-symengine

made it work
