### ISSUE TITLE
Doing derivative gives a segmentation fault

### ISSUE THREAD

**Issue by Melisius** [symengine/symengine.py#256]
When I try doing a derivative twice with the following code I get a segmentation fault. 
I have no idea what is special about what I have done below. 
I have working solutions for similar problems.

sympy.__version__ == '1.3'

symengine.__version__ == '0.3.1.dev1'

Python version ==  3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

    from symengine import symbols, Rational, sqrt, exp, log, pi

    def PW92c():
        rho_c, rho_s = symbols('rho_c rho_s', real=True)
        t,u,v,w,x,y,p = symbols('t u v w x y p', real=True)

        # Paramters
        c = 1.709921
        T = [(1-log(2))/pi**2, (1-log(2))/(2*pi**2), 0.016887]
        U = [0.21370,  0.20548,  0.11125]
        V = [7.5957, 14.1189, 10.357]
        W = [3.5876, 6.1977, 3.6231]
        X = [1.6382, 3.3662,  0.88026]
        Y = [0.49294, 0.62517, 0.49671]
        P = [1.0, 1.0, 1.0]

        # Functional
        zeta = rho_s/rho_c
        r = (Rational(3,4)/(pi*rho_c))**Rational(1,3)
        omega =((1+zeta)**Rational(4,3)+(1-zeta)**Rational(4,3)-2)/(2**Rational(4,3)-2)
        en = -2*t*(1+u*r)*log(1+1/(2*t*(v*sqrt(r)+w*r+x*r**Rational(3,2)+y*r**(p+1))))
        eps = en.subs({t:T[0],u:U[0],v:V[0],w:W[0],x:X[0],y:Y[0],p:P[0]})
        eps = eps - en.subs({t:T[2],u:U[2],v:V[2],w:W[2],x:X[2],y:Y[2],p:P[2]})*omega*(1-zeta**4)/c
        eps = eps + (en.subs({t:T[1],u:U[1],v:V[1],w:W[1],x:X[1],y:Y[1],p:P[1]}) -en.subs({t:T[0],u:U[0],v:V[0],w:W[0],x:X[0],y:Y[0],p:P[0]}))*omega*zeta**4

        return eps

    def PBEc():
        rho_c, rho_s = symbols('rho_c rho_s', real=True)
        gamma_cc = symbols('gamma_cc', real=True)

        # Parameters
        gamma = (1 - log(2))/(pi**2)
        beta = 0.066725
        e = 1
        a0 = 1

        # Functional
        kF = (3 * rho_c * pi**2)**Rational(1,3)
        ks = sqrt( 4 * kF/(pi*a0) )
        zeta = rho_s/rho_c
        phi = ( (1 + zeta)**(2/3) + (1 - zeta)**Rational(2,3) )/2
        t = sqrt(gamma_cc)/( 2 * phi * ks * rho_c )
        t2 = t**2
        ecunif = PW92c()
        A = beta/gamma*(exp(-ecunif/(gamma*phi**3*e**2/a0))-1)**(-1)
        H = (e**2/a0)*gamma*phi**3*log(1 + beta/gamma*t**2*(( 1 + A * t**2 )/( 1 + A * t**2 + A**2 * t**4 )))
        epsPBE = ecunif + H

        return epsPBE

    rho_c, rho_s = symbols('rho_c rho_s', real=True)
    gamma_cc, gamma_ss, gamma_cs = symbols('gamma_cc gamma_ss gamma_cs', real=True)

    E = PBEc().subs({rho_s: 0})*rho_c
    d1E_rhoc = E.diff(rho_c)
    d2E_rhoc2 = d1E_rhoc.diff(rho_c)

**Comment by bjodah** [comment]
Could you try to remove as many terms as possible while still causing a segfault (i.e. make a minimal example?).

**Comment by Melisius** [comment]
I have minimized the example now. The first code here gives the segmentation fault:

    from symengine import symbols, Rational, sqrt, exp, log, pi

    def PW92c():
        rho_c = symbols('rho_c', real=True)
        p = symbols('p', real=True)

        r = (Rational(3,4)/(rho_c))**Rational(1,3)
        en = r**(p+1)
        eps = en.subs({p:1.0})

        return eps

    rho_c = symbols('rho_c', real=True)
    E = PW92c()
    d1E_rhoc = E.diff(rho_c)
    d2E_rhoc2 = d1E_rhoc.diff(rho_c)


This second one here seem to work (atleast no segmentation fault):

    from symengine import symbols, Rational, sqrt, exp, log, pi

    def PW92c():
        rho_c = symbols('rho_c', real=True)
        p = symbols('p', real=True)

        r = (Rational(3,4)/(rho_c))**Rational(1,3)
        en = r**(p+1)
        eps = en.subs({p:1})

        return eps

    rho_c = symbols('rho_c', real=True)
    E = PW92c()
    d1E_rhoc = E.diff(rho_c)
    d2E_rhoc2 = d1E_rhoc.diff(rho_c)

**Comment by certik** [comment]
@Melisius I am very happy to see you using SymEngine for DFT calculations.

If the segfault is coming from SymEngine (as opposed to SymEngine.py) then recompiling in Debug mode should show where the error is coming from. Thanks for reporting it.
