### ISSUE TITLE
Running out of memory when expanding a large Boolean expression

### ISSUE THREAD

**Issue by Midnighter** [symengine/symengine.py#257]
I was trying to use `expand` on the following [Boolean expression](https://github.com/symengine/symengine.py/files/2698382/longest.txt). When I do so, symengine quickly blows through the 16 GB of memory that I have available. I have the same problem in sympy just that it takes hours not seconds there (so well done on the speed :stuck_out_tongue_winking_eye: ).

Is there a better way to expand the expression that I'm missing?

Using Python 3.6.7 and symengine 0.3.0.

**Comment by isuruf** [comment]
How do you create this Boolean expression in symengine? I don't think `or` and `and` are defined at all for symengine objects

**Comment by Midnighter** [comment]
So far we have replaced 'or' with `+` as well as 'and' with `*`. Which worked for shorter expressions. (Please note that we have worked with the sympy version of `expand` so far. I only tried symengine after seeing failures with these larger expressions.)

**Comment by isuruf** [comment]
Okay. I just tried it and the expressions blow up with expand which is expected since there'll be 82 billion products in the final sum (assuming all products are distinct)
What are you trying to do with the expanded form?

**Comment by Midnighter** [comment]
I hadn't actually estimated the combinations, thanks for that. This rule represents the various ways a particular enzyme can be assembled. This expression is supposed to represent how different genetic products can come together to form a giant complex.

My idea was to expand this expression until it is not nested any longer, at that point I would expect each possible combination of gene products of the complex to be separated by 'or', i.e., those terms connected by 'and' form one possible realization of the complex.

Whether this expression accurately represents biology and/or is constructed correctly is out of my hands.

**Comment by Midnighter** [comment]
Thank you for considering the issue. I have decided to walk an AST instead.
