### ISSUE TITLE
Complex Numbers in symengine

### ISSUE THREAD

**Issue by ronald00773** [symengine/symengine.py#264]
Is there a way to convert symengine I to 1j directly so that it's complex values can be used in regular python? The way I'm doing right now is convert to sympy object and then using the built-in complex function but this is computationally expensive. And also how to find real and imaginary parts?

**Comment by certik** [comment]
@ronald00773 did you figure it out? Was your question about how to convert SymEngine's complex type to a Python complex type efficiently? I am going to reopen this until we have a good answer here.

**Comment by certik** [comment]
@ronald00773, Isuru just implemented a direct way in #265.
