### ISSUE TITLE
Does not build with symengine 0.4.0 codegen.h in different folder

### ISSUE THREAD

**Issue by costrouc** [symengine/symengine.py#276]
Tried to build symengine.py with symengine 0.4.0 and failed to compile. Would be nice to update python library to compile with most recent version.

**Comment by isuruf** [comment]
Master of symengine.py works with 0.4.0. I'll make a release of symengine.py this weekend

**Comment by costrouc** [comment]
Thank you! I'm packaging symengine for [nixpkgs](https://github.com/NixOS/nixpkgs) and they usually prefer to use releases.

**Comment by isuruf** [comment]
Thanks for packaging symengine for nixpkgs. FYI, symengine.py supports only one version of symengine C++ library (and will probably be true until symengine reaches 1.0). The version supported is at `symengine_version.txt` file in the root folder. (It might be a git hash or a git tag). For released versions of symengine.py, it'll be a git tag.

**Comment by costrouc** [comment]
Okay great. Look forward to the 0.4.0 release. Thanks for the help.

**Comment by isuruf** [comment]
Released 0.4.0. sdist and wheels are in PyPI.
