### ISSUE TITLE
error installing symengine windows

### ISSUE THREAD

**Issue by Iamtryingtoo** [symengine/symengine.py#287]
I have tried to install symengine will pip and pip3 and get the following error:

C:\Users\David\AppData\Local\Programs\Python>pip install symengine
Collecting symengine
  Using cached https://files.pythonhosted.org/packages/1e/ac/2e795bcc9291f52c951570721b2c80db2d3ce5cc3689aafd7caf1f634dda/symengine-0.4.0.tar.gz
Building wheels for collected packages: symengine
  Building wheel for symengine (setup.py) ... error
  ERROR: Complete output from command 'c:\users\david\appdata\local\programs\python\python35-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-hq6_qnpz\\symengine\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\David\AppData\Local\Temp\pip-wheel-elodgc7r' --python-tag cp35:
  ERROR: running bdist_wheel
  running build
  running build_ext
  error: [WinError 2] The system cannot find the file specified
  ----------------------------------------
  ERROR: Failed building wheel for symengine
  Running setup.py clean for symengine
Failed to build symengine
Installing collected packages: symengine
  Running setup.py install for symengine ... error
    ERROR: Complete output from command 'c:\users\david\appdata\local\programs\python\python35-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-hq6_qnpz\\symengine\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\David\AppData\Local\Temp\pip-record-7ezq2mk4\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_ext
    error: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command "'c:\users\david\appdata\local\programs\python\python35-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\David\\AppData\\Local\\Temp\\pip-install-hq6_qnpz\\symengine\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\David\AppData\Local\Temp\pip-record-7ezq2mk4\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\David\AppData\Local\Temp\pip-install-hq6_qnpz\symengine\

**Comment by isuruf** [comment]
We stopped building windows 32 bit wheels. Can you use a 64 bit python? If not, you'll have to compile SymEngine yourself.

**Comment by Iamtryingtoo** [comment]
Thank you I will download the 64-bit python.
