### ISSUE TITLE
memory leak in diff()

### ISSUE THREAD

**Issue by ichumuh** [symengine/symengine.py#293]
I've noticed that my software sometimes runs out of memory. I do a lot of jacobians on huge expressions and managed to condense it into this example:
```
import gc
import os
import psutil
import symengine as se


@profile
def muh():
    symbols = [se.Symbol(x) for x in 'abcdefghijklmopqr']

    expr = se.Symbol('a')
    for s in symbols: # build some random big expression
        expr = se.sqrt(s) + se.log(s) / expr - expr * expr

    a = expr.diff('a')
    b = str(a)
    print('length of expression: {}'.format(len(b)))


process = psutil.Process(os.getpid())
print('current memory usage before: {} mb'.format(process.memory_info()[0] / 1000000.))
muh()
gc.collect()  # trigger garbage collector just in case?
print('current memory usage after: {} mb'.format(process.memory_info()[0] / 1000000.))
```
Here is the output of a memory profiler:
```
$ python -m memory_profiler muh2.py
current memory usage before: 59.580416 mb
length of expression: 55705628
current memory usage after: 260.743168 mb
Filename: muh2.py

Line #    Mem usage    Increment   Line Contents
================================================
     7   56.820 MiB   56.820 MiB   @profile
     8                             def muh():
     9   56.820 MiB    0.000 MiB       symbols = [se.Symbol(x) for x in 'abcdefghijklmopqr']
    10                             
    11   56.820 MiB    0.000 MiB       expr = se.Symbol('a')
    12   56.820 MiB    0.000 MiB       for s in symbols: # build some random big expression
    13   56.820 MiB    0.000 MiB           expr = se.sqrt(s) + se.log(s) / expr - expr * expr
    14                             
    15  221.836 MiB  165.016 MiB       a = expr.diff('a')
    16  301.793 MiB   79.957 MiB       b = str(a)
    17  301.793 MiB    0.000 MiB       print('length of expression: {}'.format(len(b)))
```
You may notice that the 60mb from before the function call + 165 from the diff only add up to 225mb, so this `str()` might also cause some leak. Maybe because of the `__str__` implementation. When I remove lines 16 and 17, the memory usage after the call is 232mb. When I also remove the assignment to `a` in line 15, there is no leak.

**Comment by certik** [comment]
@ichumuh  Thanks for the test. I modified it to the following:
```python
import gc
import os
import psutil
import symengine as se


def muh():
    symbols = [se.Symbol(x) for x in 'abcdefghijklmopqr']

    expr = se.Symbol('a')
    for s in symbols: # build some random big expression
        expr = se.sqrt(s) + se.log(s) / expr - expr * expr

    a = expr.diff('a')
    b = str(a)
    print('length of expression: {}'.format(len(b)))


process = psutil.Process(os.getpid())
print('current memory usage before: {} mb'.format(process.memory_info()[0] / 1000000.))
while True:
    muh()
gc.collect()  # trigger garbage collector just in case?
print('current memory usage after: {} mb'.format(process.memory_info()[0] / 1000000.))
```
I ran this for over 30 iterations. I observed that every time the `muh` function ends, the memory usage drops to exactly 223MB. So there doesn't seem to be recurring leaks during the iterations. There might be some initial leaks, because one would think the memory usage should drop to 0.
While the `muh` function runs, the maximum memory that I observed was ~380MB.

So there still seem to be two questions:

1. Why does it need ~300MB memory?
2. Why isn't all the memory reclaimed when the `muh` function ends?

**Comment by ichumuh** [comment]
I repeated your experiment and got the same results. So it seems like the expressions in my code got so big that 16gb of ram are not enough to compute the jacobian, even if its the first one I calculate. So even if the leak is fixed I will still have a problem.

> P.S. I used the latest python-symengine package from conda-forge.

I used the latest version from github.

**Comment by isuruf** [comment]
@ichumuh, this is unrelated to the memory problem, but try using https://github.com/symengine/symengine/pull/1583/commits/1049f2c9721d6636f3445220290edeb154363f23.

**Comment by ichumuh** [comment]
@isuruf I guess you want to know how it affects the time I spend computing jacobians? I repeated one of my tests a couple times and with [`c66b8c5`](https://github.com/symengine/symengine/commit/c66b8c50bb481c51ce128b768b056454aa6dc67a) it spend on average `45.2`s computing jacobians and with [`8cada10`](https://github.com/symengine/symengine/commit/8cada103d20ff0fa25b64a8b5dc8487d2da1c27c) `46.725`s. But if we look at the best run for both commits, its about the same, so it might just be some noise.

**Comment by isuruf** [comment]
@ichumuh, can you try https://github.com/symengine/symengine/pull/1592 as well?

**Comment by ichumuh** [comment]
This got fixed by https://github.com/symengine/symengine/pull/1592.
