### ISSUE TITLE
debug build shared lib is stripped with make install

### ISSUE THREAD

**Issue by rwst** [symengine/symengine.py#30]
Using `python setup.py install` is fine but `make install` is not. Using `readelf --debug-dump=decodedline /usr/lib64/python2.7/site-packages/symengine/lib/symengine_wrapper.so` we can see the latter strips debug info from the file.

So I would explicitly decourage using `make install` in the documentation for such noobs as myself.

**Comment by isuruf** [comment]
Only difference between the two methods I see is that `python setup.py install` adds `-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=yes` to cmake by default. Does this make the change?

**Comment by certik** [comment]
`setup.py install` is using `make install`, doesn't it?

**Comment by rwst** [comment]
OK, that was false alarm. I rechecked and `make install` does what's expected. Sorry for the fuss.
