### ISSUE TITLE
conflict with other package yielding segmentation fault

### ISSUE THREAD

**Issue by Karrenbelt** [symengine/symengine.py#306]
on OSX 10.15.1, with this package: http://libroadrunner.org

if I import symengine and then roadrunner, I get only the fault reported
if I import roadrunner first, then symengine I get the following error

`Assertion failed: (!NextRegistered && "argument multiply registered!"), function addArgument, file /Users/phantom/etc/src/llvm-3.5.2/llvm-3.5.2.src/lib/Support/CommandLine.cpp, line 108.`

**Comment by certik** [comment]
@Karrenbelt thanks for reporting it. How do you install SymEngine? From your error perhaps SymEngine and libroadrunner are both using LLVM, but different version? I don't know if that could cause it.

**Comment by certik** [comment]
@Karrenbelt this should be fixed thanks to @isuruf. Please let us know if you are still encountering the error.

**Comment by Karrenbelt** [comment]
In python3.6 I still get the same error I reported initially

In python3.7:
roadrunner first, then symengine imported, I obtain:

```
: CommandLine Error: Option 'use-dbg-addr' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

other way around it works on import. However, when I install it in my repository and run my tests, which never import symengine but do use roadrunner, these will no longer run, unless I uninstall symengine again.

**Comment by bjodah** [comment]
libroadrunner uses LLVM, you'll need to compile it yourself and make sure to use a matching version.

**Comment by isuruf** [comment]
@Karrenbelt, how did you install LLVM?

@bjodah, if LLVM is statically linked in with the symbols hidden, then there's no need for matching versions.

**Comment by bjodah** [comment]
@isuruf that's true, but I think LLVM is large enough that a shared library approach is preferable (if possible).

**Comment by Karrenbelt** [comment]
no I have not installed it, roadrunner needs 3.2 - 3.5, symengine needs 3.8 for macOS, and brew doesn't find llvm33 as recommended by roadrunner here [http://libroadrunner.org/build-roarunner-from-source/linux-build-distribution/](url), nor can I brew install symengine. Anyway, since I am getting a new computer soon which will be running Ubuntu and using a Debian package manager, I decided not to spend the effort to try and fix this on my OSX platform.

**Comment by isuruf** [comment]
@bjodah, true, but for wheels, static linking is the only option.

@Karrenbelt, we haven't built new wheels yet, but when they are built, they should probably work. @bjodah, @certik, if you have access to OSX, can you check?
