### ISSUE TITLE
(minor) provide convenience rational creator

### ISSUE THREAD

**Issue by rwst** [symengine/symengine.py#31]
It's not in `__init__.py` and if it were tested tests would not pass. I get a `Teuchos::throw_null_ptr_error` from the simple `Rational(-1,2)`.

I would consider this a blocker for any release.

**Comment by isuruf** [comment]
`__cinit__` methods are not there for types that needs input in a canonical form.
Is there a way in Python to return an `Integer` for `Rational(2, 1)`?

**Comment by certik** [comment]
We can just wrap `rational()` and then things should work. Similar to how we wrap `integer`.

**Comment by rwst** [comment]
Actually there is a class defined: https://github.com/symengine/symengine.py/blob/master/symengine/lib/symengine_wrapper.pyx#L744
It is used in `c2py` for conversion of `symengine.Rational`.

I'm no longer sure if this ticket is really needed because the only place where I would use it is in test files and there I can use `Integer/Integer` instead. I'll edit the ticket title accordingly.

**Comment by certik** [comment]
C2py always get the input in canonical form, so there is no issue in that
function.
