### ISSUE TITLE
Store objects from symengine environment with dill

### ISSUE THREAD

**Issue by karan-an-1996** [symengine/symengine.py#336]
Hi everyone,

I am trying to save an Add expression of the symengine.lib.symengine_wrapper module with dill, however, I get the following error 'TypeError: self.thisptr cannot be converted to a Python object for pickling'. 

Is there a way to store the object without converting it to the sympy environment?

Regards, Karan

**Comment by rikardn** [comment]
This is a good question! I encountered the same issue today myself and solved it by going via sympy, which is not optimal. Serialization on the C++ side is being worked on here https://github.com/symengine/symengine/pull/1704. It could potentially be possible to support serialization directly in the python wrapper, but I don't know if it is worth it or if the C++ serializer could work also for pickling in python.

**Comment by isuruf** [comment]
> It could potentially be possible to support serialization directly in the python wrapper, but I don't know if it is worth it or if the C++ serializer could work also for pickling in python.

C++ serializer should definitely work also for pickling in python.

**Comment by isuruf** [comment]
Fixed in #377
