### ISSUE TITLE
Adopt NEP 29

### ISSUE THREAD

**Issue by rikardn** [symengine/symengine.py#360]
I think symengine.py should adopt NEP 29: https://numpy.org/neps/nep-0029-deprecation_policy.html

This is currently under discussion for sympy (https://github.com/sympy/sympy/issues/21884) and it seems as if there is an agreement to do this.

Since NEP 29 is followed by numpy also other major packages of the scientific python infrastructure, like scipy and pandas have to follow. If now also sympy adopts it I don't think there is much to gain for symengine.py to support older python versions.

If we would adopt NEP 29 today we could immediately stop testing on Python 3.6 and at the end of the year also stop testing for Python 3.7.

**Comment by isuruf** [comment]
I don't know if adopting NEP 29 gains us anything. There's nothing we are using that is python 3.7+ only. numpy, sympy all benefit from adopting newer python versions, but with symengine being a very thin wrapper written using Cython, I don't think we'd gain anything.

**Comment by rikardn** [comment]
Thanks @isuruf for your opinion.

What we gain is to not have to test symengine as many versions of Python. Since the rest of the scientific python ecosystem, with sympy in particular, is using or moving towards NEP 29 I figured the downsides were small.

That being said I agree that there are no other upsides as in being able to use new features of new Python versions. As an option to NEP 29 we should at least remove testing for python versions going end of life, but that I guess is what we have done so far.
