### ISSUE TITLE
PyPI v0.8.1 source misses files

### ISSUE THREAD

**Issue by ccoulombe** [symengine/symengine.py#367]
The archive for v0.8.1 misses the files :
- [cmake/version_script.txt](https://github.com/symengine/symengine.py/blob/master/cmake/version_script.txt)
- [cmake/get_suffix.py](https://github.com/symengine/symengine.py/blob/master/cmake/get_suffix.py)

Which are required to build it seems.

**Comment by isuruf** [comment]
@ccoulombe, can you check the master? If it works, I can release a new patch version.

**Comment by ccoulombe** [comment]
Building from the master branch worked before and this is what I ended up doing.
The archive on PyPI were missing the files. I believe the file is the same as https://github.com/symengine/symengine.py/releases/download/v0.8.1/symengine-0.8.1.tar.gz which lacks the two files.

Including the missing files in the manifest looks like it will solve the issue, but I cannot validate until the release is perhaps edited.

**Comment by isuruf** [comment]
Can you try https://github.com/isuruf/isuruf.github.io/releases/download/v1.0/symengine-0.8.1.tar.gz ?

**Comment by ccoulombe** [comment]
Yes, this latest archive works! I successfully built the wheel with it. :+1:
