### ISSUE TITLE
Update to new symengine

### ISSUE THREAD

**Issue by Sumith1896** [symengine/symengine.py#38]
`diff` method got refactored.

**Comment by rwst** [comment]
The fix for the redeclaration of `diff` is simple but this is not all. Major drawback is that Cython has no `std::multiset` which is used as return value of `SymEngine::Derivative::get_symbols`.

**Comment by isuruf** [comment]
@rwst, that issue is fixed here, https://github.com/symengine/symengine.py/pull/43, but there's still some more work for series. I won't be able to look into this till next week.

**Comment by Sumith1896** [comment]
Can be closed via https://github.com/symengine/symengine.py/pull/45 ?

**Comment by certik** [comment]
Yes, this is fixed.

**Comment by rwst** [comment]
@isuruf Agree that there is more work. For starters, it's soo slow, try
interrupting, it's somewhere in SymPy.

**Comment by rwst** [comment]
It's https://github.com/sympy/sympy/issues/10262 again.
