### ISSUE TITLE
`Interval` object API (sympy compat)

### ISSUE THREAD

**Issue by richardotis** [symengine/symengine.py#380]
The `Interval` object has an inconsistency with sympy in how the objects are defined. Here's an example:

sympy: `Interval(S.NegativeInfinity, S.Infinity, left_open=True, right_open=True)`
symengine: `Interval(S.NegativeInfinity, S.Infinity, True, True)` (kwargs not allowed)

`Interval` objects in sympy are also missing the `.start` and `.end` attributes and are currently only accessible via `.args[0]` and `.args[1]`, respectively.

**Comment by isuruf** [comment]
Should be easy to fix. Want to do a PR?

**Comment by richardotis** [comment]
Sure. Let me see if I can get a development environment setup.

**Comment by richardotis** [comment]
Getting a bunch of linker errors getting the symengine shared library to build on Windows. I'll have to return to this later in the week.

**Comment by isuruf** [comment]
Would be interested to know your setup to see how we can fix that in symengine.

**Comment by richardotis** [comment]
I managed to get an environment running inside Gitpod.
