### ISSUE TITLE
Piecewise cannot typecasted into number even if all conditions are evaluated.

### ISSUE THREAD

**Issue by nkanazawa1989** [symengine/symengine.py#393]
This is feature request for `Piecewise` to be automatically simplified when all conditions are evaluated.

Currently this code doesn't work due to `NotImplemented` error.
```python
t = Symbol("t")
f = Piecewise((1j, t > 1), (1, True))
complex(f.subs(t, 0))
```

We always need to write
```python
complex(f.subs(t, 0).simplify())
```
This looks like bit redundant and may cause performance issue (especially when this code is written in a function taking arbitrary `f`, i.e. unnecessary simplify is always called).

version: 0.8.1

**Comment by isuruf** [comment]
See https://github.com/symengine/symengine/pull/1890
