### ISSUE TITLE
Support for complex numbers in expressions passed to Lambdify

### ISSUE THREAD

**Issue by wshanks** [symengine/symengine.py#396]
`Lambdify` currently does not support complex expressions. Would it be possible for them to be supported?

Here is an example:

```python
import symengine as sym

t = sym.Symbol("t")

func = sym.Lambdify(t, sym.I * t)

func(5)
```

This gives me:

```
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_429585/3682074719.py in <module>
      3 t = sym.Symbol("t")
      4 
----> 5 func = sym.Lambdify(t, sym.I * t)
      6 
      7 func(5)

symengine_wrapper.pyx in symengine.lib.symengine_wrapper.Lambdify()

symengine_wrapper.pyx in symengine.lib.symengine_wrapper._Lambdify.__init__()

symengine_wrapper.pyx in symengine.lib.symengine_wrapper.LambdaDouble._init()

RuntimeError: Not Implemented
```

I get this for symengine 0.8.1 and 0.9.2 with Python 3.9 on Linux.

**Comment by isuruf** [comment]
Try `func = sym.Lambdify(t, sym.I * t, real=False)`

**Comment by wshanks** [comment]
:facepalm: Sorry, I keep tripping over differences between sympy and symengine!

**Comment by isuruf** [comment]
The difference is due to performance reasons. `real=True` is faster compared to `real=False`, and to get that extra speed boost we have the `real=True` default.
