### ISSUE TITLE
Derivative of a complex function raises a segmentation violation

### ISSUE THREAD

**Issue by MWalbecq** [symengine/symengine.py#407]
I try to compute the derivative of a complex equation with the following program :
```
from symengine import Symbol, I

x = Symbol('x')
equation = (-x)**I

print(equation.diff(x))
```
But instead of `-I*(-x)**(-1 + I)` or something equivalent, the program stops and a memory access violation is raised :
> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

Maybe it is related to the minus sign before the x because the program works perfectly when I remove it :
```
from symengine import sin, Symbol, I

x = Symbol('x')
equation = (x)**I

print(equation.diff(x))
```
I get the correct answer : `I*x**(-1 + I)`
Is there anything I can do to compute this derivative without interrupting the program ?

**Comment by rikardn** [comment]
Thanks for reporting this. I can confirm that this indeed leads to a segfault.
