### ISSUE TITLE
Sympy-symengine roundtrip failure

### ISSUE THREAD

**Issue by nkanazawa1989** [symengine/symengine.py#409]
Symengine doesn't get identical expression after `sympify`ed with SymPy.
```python
import sympy, symengine

a, b = symengine.symbols("a b")
expr = - ((1/2) * a - (1/2) * b)
expr_roundtrip = symengine.sympify(sympy.sympify(expr))

expr == expr_roundtrip  # false
```

This is because sympy automatically (implicitly) does expand to the expression.
```
expr  # -(0.5*a - 0.5*b)
expr_roundtrip  # -0.5*a + 0.5*b
```

This works
```python
import sympy, symengine


a, b = symengine.symbols("a b")
expr = - ((1/2) * a - (1/2) * b)
expr = expr.expand()
expr_roundtrip = symengine.sympify(sympy.sympify(expr))

expr == expr_roundtrip  # true
```

This use case is sometimes important because symengine doesn't support serialization of expressions, i.e.

```python
import symengine, sympy

expr_txt = sympy.srepr(sympy.sympify(expr))  # save this in file-like object
expr_roundtrip = symengine.sympify(sympy.parse_expr(expr_txt))  # retrieve
```

**Comment by isuruf** [comment]
> This use case is sometimes important because symengine doesn't support serialization of expressions, i.e.

symengine does support pickle. You can also convert to string and parse it back, but `pickle.dumps` is preferred over this method.

**Comment by mtreinish** [comment]
Is there a method to extract the cereal generated data without using pickle? Similarly is there also a way to create a new expression object directly from the serialized representation? In the use case @nkanazawa1989 and I are working on we can't use the pickle module because it opens up an opportunity for arbitrary code execution so we need a way to serialize and recreate an expression object directly using symengine's api.

**Comment by isuruf** [comment]
Loading is a separate method already. https://github.com/symengine/symengine.py/blob/master/symengine/lib/symengine_wrapper.pyx#L829-L830
Can do the same for saving at https://github.com/symengine/symengine.py/blob/master/symengine/lib/symengine_wrapper.pyx#L843-L845

One issue is that we are using pickle internally for `Symbol` subclasses which means there's an opportunity for arbitrary code execution. So, you'll have to make sure you don't have `Symbol` subclasses.

**Comment by nkanazawa1989** [comment]
Thanks @isuruf I found one (probably) edge case:

```python
import pickle
import symengine as sym

val = sym.symbols("val")
expr = sym.I * val

pickle.loads(pickle.dumps(expr))
```
This works, however, when I apply complex double coefficient
```python
import pickle
import symengine as sym

val = sym.symbols("val")
expr = 1.0 * sym.I * val

pickle.loads(pickle.dumps(expr))
```
raises
```
RuntimeError: /Users/runner/miniforge3/conda-bld/symengine-wheels_1646701063069/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/symengine/serialize-cereal.h:653: RCP<const SymEngine::Basic> SymEngine::load_basic(Archive &, RCP<const T> &, typename std::enable_if<!(std::is_base_of<Relational, T>::value || std::is_base_of<OneArgFunction, T>::value || std::is_base_of<MultiArgFunction, T>::value || std::is_base_of<TwoArgFunction, T>::value), int>::type *) [Archive = cereal::PortableBinaryInputArchive, T = SymEngine::ComplexDouble]Loading of this type is not implemented.
```
though it can generate some binary (just cannot load). So seems like we still need to rely on sympy parser (and thus we need implicit expand in symengine), or upgrade symengine deserializer in this case.

**Comment by isuruf** [comment]
Should be fixed with https://github.com/symengine/symengine/pull/1913
