### ISSUE TITLE
Python bindings fail to build when Teuchos gets disabled in SymEngine

### ISSUE THREAD

**Issue by yurivict** [symengine/symengine.py#415]
In such case Python bindings still look for libteuchos.a

Python bindings should auto-detect SymEngine options and not expect from it what it doesn't have.

**Comment by isuruf** [comment]
I'm not sure this is true. I build the python bindings against SymEngine with Teuchos disabled all the time and haven't run into an issue. Do you have a reproducer?

**Comment by yurivict** [comment]
I can't reproduce this at this moment any more.
