### ISSUE TITLE
std::badalloc in sympify()

### ISSUE THREAD

**Issue by Evan-Zhao** [symengine/symengine.py#419]
The following code throws a `MemoryError: std::bad_alloc` error:
```python
import symengine as se
se.sympify("Equality(sp_0_0 * sp_1_0, 1) & Equality(10 / (sp_1_2 * sp_1_3) / sp_1_1 / sp_1_0, 1)")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "symengine_wrapper.pyx", line 522, in symengine.lib.symengine_wrapper.sympify
MemoryError: std::bad_alloc
```

This _also_ fails with the same error:
```python
se.sympify("And(Equality(sp_0_0 * sp_1_0, 1), Equality(10 / (sp_1_2 * sp_1_3) / sp_1_1 / sp_1_0, 1)))")
```

Meanwhile, this doesn't throw _but_ it does not recognize `Equality` as a symengine function, and returns undefined function symbol:
```
>>> e = se.sympify("Equality(sp_0_0 * sp_1_0, 1)")
>>> type(e)
<class 'symengine.lib.symengine_wrapper.FunctionSymbol'>
```
Therefore the following also fails, but with a much friendlier message:
```
>>> e = se.sympify("Equality(sp_0_0 * sp_1_0, 1)")
>>> se.And(e, e)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "symengine_wrapper.pyx", line 1480, in symengine.lib.symengine_wrapper.And.__new__
  File "symengine_wrapper.pyx", line 4287, in symengine.lib.symengine_wrapper.logical_and
TypeError: Cannot convert FunctionSymbol to symengine.lib.symengine_wrapper.Boolean
```

SymPy can parse all 3 expressions just fine.

It seems there are 2 issues: `sympify` not recognizing `Equality` as a built-in function, and constructors `And`, `Or`, etc. rejecting `FunctionSymbol` in a really user-unfriendly way.

I'm using symengine 0.92 with Python 3.9.

**Comment by isuruf** [comment]
This is a bug in the C++ library. Until that is fixed, can you use `Eq` instead of `Equality`?
