### ISSUE TITLE
Returned solution of A*x=b via A.LUsolve(b) cannot be worked with

### ISSUE THREAD

**Issue by hpaantee** [symengine/symengine.py#442]
I have a system of equations `Ax=b`. A has a shape of 576x576.
Here, A is a sparse matrix where some entries might contain a symbol.
I can use `x = A.LUsolve(b)` just fine (~30) to solve for a symbolic solution of `x`.

However, I can't do anything with the result. `Lambdify` gives the following RuntimeError:
```
f = symengine.Lambdify([v], x)
File "symengine_wrapper.pyx", line 5276, in symengine.lib.symengine_wrapper.Lambdify
File "symengine_wrapper.pyx", line 4856, in symengine.lib.symengine_wrapper._Lambdify.__init__
File "symengine_wrapper.pyx", line 5091, in symengine.lib.symengine_wrapper.LLVMDouble._init
RuntimeError: -1.14183378644392e+50 + 8.20975478115991e+48*I
```
Substituting x and converting to numpy or printing the first element does never return. 
Here is my code, matrix A is loaded from a file via sympy:
```
import sympy
from sympy.parsing.sympy_parser import parse_expr
import symengine

with open('matrix_A.txt', 'r') as f:
    A = parse_expr(f.read())
b = sympy.zeros(576, 1)
b[0,0] = 1
A = symengine.Matrix(A)
b = symengine.Matrix(b)
x = A.LUsolve(b)
print('solved!')
v = symengine.var('w01 Efield_01')
f = symengine.Lambdify([v], x)
```
Am I doing something wrong or am I just hitting some limitation? 
Here is the attached file:
[matrix_A.txt](https://github.com/symengine/symengine.py/files/11679468/matrix_A.txt)

**Comment by isuruf** [comment]
Note that the expressions are huge. For eg:
```
In [7]: symengine.count_ops(x)
Out[7]: 3823017280
```

Try doing
```
f = symengine.Lambdify([v], x, real=False, cse=True)
```

**Comment by hpaantee** [comment]
Thanks a lot, which those parameters in Lambdify I could successfully use the returned function!

**Comment by hpaantee** [comment]
Sorry to reopen this, but the problem somewhat persists. I generated a slightly different `A` for what Lambdify again does never return. Interestingly enough though, 
```
In [2]: symengine.count_ops(x)
Out[2]: 10704814
```
gives a much smaller number than previously. Again I attached a minimal working example to reproduce the issue:
```
import sympy
import symengine
import pickle
with open('matrix_Ab.txt', 'rb') as f:
    A, b = pickle.load(f)
A = symengine.Matrix(A)
b = symengine.Matrix(b)
print('solve...')
x = A.LUsolve(b)
print('solved!')
print(f'Symbolic operations: {symengine.count_ops(x)}')
v = symengine.var('w_01 Efield_01')
f = symengine.Lambdify([v], x, real=False, cse=True)
```
[matrix_Ab.txt](https://github.com/symengine/symengine.py/files/11882210/matrix_Ab.txt)

**Comment by hpaantee** [comment]
Can be closed, with a slightly different matrix A it works
