### ISSUE TITLE
new release please - 0.10.0 fails due to Cython 3 issues

### ISSUE THREAD

**Issue by dimpase** [symengine/symengine.py#456]
I can build the current branch, but 0.10.0 fails for me on Gentoo Linux with gcc 13 and Cython 3.0.5. Time for a new release I suppose,

**Comment by isuruf** [comment]
Will do this weekend. Thanks for the reminder.

**Comment by dimpase** [comment]
ping?

**Comment by isuruf** [comment]
Waiting for https://github.com/pypi/support/issues/3369
cc @rikardn

**Comment by dimpase** [comment]
I wonder if switching to using `gmpy2` would be feasible - at least it would lower the size of wheels.

**Comment by isuruf** [comment]
Should be fixed now
