### ISSUE TITLE
"AttributeError: module 'symengine' has no attribute 'lib'" ?

### ISSUE THREAD

**Issue by kiki1123** [symengine/symengine.py#472]
Please, how do I fix "AttributeError: module 'symengine' has no attribute 'lib'" ?

For instance, when I run this line : " expr2 = se.lib.symengine_wrapper.Add(expr)". I get this error.

**Comment by rikardn** [comment]
I am not sure what you are trying to do.

To add two terms together you would do:

```python

import symengine

x = symengine.Integer(1)
y = symengine.Integer(2)

x + y
>>> 3
```

or

```python
import symengine

symengine.Add(1, 2)
>>> 3
```

The public API can be imported directly from `symengine` and there is usually no need to dig into the `symengine_wrapper` module.

**Comment by kiki1123** [comment]
Hi, thank you for your reply! I am just trying to run a code I found online.
