### ISSUE TITLE
Symengine.py-0.11.0 fails after symengine was upgraded to 0.12.0: static assertion failed due to requirement '__is_cpp17_move_insertable<std::allocator<SymEngine::LLVMDoubleVisitor>, void>::value': The specified type does not meet the requirements of Cpp17MoveInsertable

### ISSUE THREAD

**Issue by yurivict** [symengine/symengine.py#484]
See the log [here](https://pkg-status.freebsd.org/beefy22/data/140amd64-default/a18cb4bedd61/logs/py311-symengine-0.11.0.log).

Could you please make a release compatible with symengine-0.12.0?

Clang-18
FreeBSD 14.1

**Comment by certik** [comment]
I think we need to make a new release of symengine.py-0.12.0?

**Comment by yurivict** [comment]
Your current master revision also doesn't build with symengine-0.12.0

**Comment by isuruf** [comment]
Duplicate of https://github.com/symengine/symengine.py/issues/483
