### ISSUE TITLE
'.subs' Error

### ISSUE THREAD

**Issue by strukturen** [symengine/symengine.py#486]
If I call the following in Python instead of throwing an error it crashes Python. Can I somehow solve this so that it can throw an exception?

Example:
```python
import symengine as spe
expr = spe.sympify('sin(log(t))')
t = spe.symbols('t')
expr.subs({t:0})
```

However, if I just execute `spe.sin(spe.log(0))` it throws me an error.

**Comment by isuruf** [comment]
Fixed in https://github.com/symengine/symengine.py/pull/487
