### ISSUE TITLE
Segfault on OS X El Capitan

### ISSUE THREAD

**Issue by phantomas1234** [symengine/symengine.py#55]
I am on OS X El Capitan 10.11.3, running python 3.3 in a conda environment (tried python 3.4 as well, same issue). I build symengine from commit b5c453f73152dc1b0ec3a39186e5137d48061655 (the one supported by symengine.py) using cmake and then `python setup.py install build --symengine-dir=../symengine/` in a3acc765ba286fe8fc9ce40d7b2ff95794b8656b of symengine.py

    In [1]: from symengine import Add, var

    In [2]: v = var('x')

    In [3]: Add(v, v)

    Segfault caught. Printing stacktrace:

    Traceback (most recent call last):

    Done. Exiting the program.
    /Users/niso/anaconda/envs/optlang3.3/bin/python.app: line 3: 12878 Abort trap: 6           /Users/niso/anaconda/envs/optlang3.3/python.app/Contents/MacOS/python "$@"

Same problem with `symengine.Mul`.

Running
    v + v
runs fine though, which is weird (I think).

**Comment by certik** [comment]
Thanks for reporting this.

Yes, we currently behave differently than sympy in that you should not use Add(x, x), but x+x, since the result is Mul(2, x). If you compile symengine in Debug mode, it should raise an exception.

We should think how to best fix this.

**Comment by isuruf** [comment]
`from symengine.sympy_compat import Add` gives a sympy compatible `Add` class, which can do this.
