### ISSUE TITLE
Desired SymPy API Methods and functions

### ISSUE THREAD

**Issue by phantomas1234** [symengine/symengine.py#59]
Based on a discussion on gitter, here the functions that I'd personally would love to see in symengine.py.

For Add and Mul etc.
- [x] .is_Add
- [x] .is_Mul
- [x] .is_Atom
- [x] .is_Number
- [x] .atoms
- [x] .as_coefficients_dict
- [x] .xreplace

and
- [x] sympy.Integer
- [x] sympy.RealNumber
- [ ] sympy.PolynomialError

**Comment by certik** [comment]
Thanks @phantomas1234 for the suggestions. That shouldn't be hard to implement.

**Comment by isuruf** [comment]
@phantomas1234, 
- For RealNumber, use RealMPFR for arbitrary precision including double precision, RealDouble for just double precision)
- `.subs `should be equivalent to `.xreplace`

Polynomial support is something we are looking at implementing this summer.

**Comment by isuruf** [comment]
@phantomas1234, everything is implemented now except PolynomialError. We will add that once Polynomials are fully implemented in SymEngine.

**Comment by phantomas1234** [comment]
@isuruf That's is very cool, thanks! I'll give symengine another try now and see if I can work around PolynomialError. It also great that symengine and the bindings can easily be installed with conda now 👍
